### ISSUE TITLE
optimize field-size for form-builders (full, half, third)

### ISSUE THREAD

**Issue by trendschau** [typemill/typemill#84]
If you want to position two fields in one line (e.g. in the theme configuration), then use the new attribute "fieldsize" in your yaml-definition like this:

```
field: 
  type: text
  label: MyText
  fieldsize: half
```
